// Generated by Grafana k6 Studio (1.8.0) on 2025-10-28T14:22:13.396Z

import { group, sleep, check } from "k6";
import http from "k6/http";
import execution from "k6/execution";

export const options = {
  stages: [
    { target: 20, duration: "1m" },
    { target: 20, duration: "3m30s" },
    { target: 0, duration: "1m" },
  ],
};

export default function () {
  let params;
  let resp;
  let match;
  let regex;
  let url;
  const correlation_vars = {};

  group("Default group", function () {
    params = {
      headers: {
        "sec-ch-ua": `"Google Chrome";v="141", "Not?A_Brand";v="8", "Chromium";v="141"`,
        "sec-ch-ua-mobile": `?0`,
        "sec-ch-ua-platform": `"Windows"`,
        "upgrade-insecure-requests": `1`,
        accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
        "sec-fetch-site": `none`,
        "sec-fetch-mode": `navigate`,
        "sec-fetch-user": `?1`,
        "sec-fetch-dest": `document`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-ES,es;q=0.9`,
        priority: `u=0, i`,
      },
      cookies: {},
    };

    url = http.url`https://colibri-frontend.vercel.app/`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        pragma: `no-cache`,
        "cache-control": `no-cache`,
        accept: `*/*`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-dest": `empty`,
        referer: `https://colibri-frontend.vercel.app/sw.js`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-ES,es;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
    };

    url = http.url`https://colibri-frontend.vercel.app/index.html`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });
  });
  sleep(1);
  group("Login", function () {
    params = {
      headers: {
        accept: `*/*`,
        "access-control-request-method": `POST`,
        "access-control-request-headers": `content-type`,
        origin: `https://colibri-frontend.vercel.app`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-site": `cross-site`,
        "sec-fetch-dest": `empty`,
        referer: `https://colibri-frontend.vercel.app/`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-ES,es;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
    };

    url = http.url`https://colibri-backend-od5b.onrender.com/auth/login`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 204": (r) => r.status === 204 });

    params = {
      headers: {
        "sec-ch-ua-platform": `"Windows"`,
        "sec-ch-ua": `"Google Chrome";v="141", "Not?A_Brand";v="8", "Chromium";v="141"`,
        "content-type": `application/json`,
        "sec-ch-ua-mobile": `?0`,
        accept: `*/*`,
        origin: `https://colibri-frontend.vercel.app`,
        "sec-fetch-site": `cross-site`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-dest": `empty`,
        referer: `https://colibri-frontend.vercel.app/`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-ES,es;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
    };

    url = http.url`https://colibri-backend-od5b.onrender.com/auth/login`;
    resp = http.request(
      "POST",
      url,
      `{"email":"correo@gmail.com","password":"12"}`,
      params,
    );

    check(resp, { "status equals 400": (r) => r.status === 400 });

    params = {
      headers: {
        accept: `*/*`,
        "access-control-request-method": `POST`,
        "access-control-request-headers": `content-type`,
        origin: `https://colibri-frontend.vercel.app`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-site": `cross-site`,
        "sec-fetch-dest": `empty`,
        referer: `https://colibri-frontend.vercel.app/`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-ES,es;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
    };

    url = http.url`https://colibri-backend-od5b.onrender.com/auth/login`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 204": (r) => r.status === 204 });

    params = {
      headers: {
        "sec-ch-ua-platform": `"Windows"`,
        "sec-ch-ua": `"Google Chrome";v="141", "Not?A_Brand";v="8", "Chromium";v="141"`,
        "content-type": `application/json`,
        "sec-ch-ua-mobile": `?0`,
        accept: `*/*`,
        origin: `https://colibri-frontend.vercel.app`,
        "sec-fetch-site": `cross-site`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-dest": `empty`,
        referer: `https://colibri-frontend.vercel.app/`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-ES,es;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
    };

    url = http.url`https://colibri-backend-od5b.onrender.com/auth/login`;
    resp = http.request(
      "POST",
      url,
      `{"email":"test@colibri.com","password":"1234"}`,
      params,
    );

    check(resp, { "status equals 200": (r) => r.status === 200 });
  });
  sleep(1);
}
